version: '3.8'
services:
  my-doctor-bend:
    build: .
    image: i3z101/my-doctor-bend
    container_name: my-doctor-bend
    environment:
      - ACCOUNT_ID=PUT YOURS
      - AUTH_TOKEN=PUT YOURS
      - SERVICE_SID=PUT YOURS
      - TOKEN_SECRET_KEY=PUT YOURS
      - DB_USERNAME=PUT YOURS
      - DB_PASSWORD=PUT YOURS
    ports:
      - '5000:5000'
    volumes:
      - doctors:/app/public/doctors
      - bills:/app/public/bills
volumes:
  doctors:
  bills: