version: '3.8'
services:
  my-doctor-bend:
    build: .
    image: i3z101/my-doctor-bend
    container_name: my-doctor-bend
    environment:
      - ACCOUNT_ID=PUT URS TWILLIO ACCOUNT ID
      - AUTH_TOKEN=PUT URS TWILLIO AUTH TOKEN
      - SERVICE_SID=PUT URS TWILLIO SERVICE SID
      - TOKEN_SECRET_KEY=PUT URS JWT TOKEN SECRET
      - DB_USERNAME=PUT URS DB USERNAME
      - DB_PASSWORD=PUT URS DB PASSWORD
    ports:
      - '5000:5000'
    volumes:
      - doctors:/app/public/doctors
      - bills:/app/public/bills
volumes:
  doctors:
  bills: